import {
  Boxes,
  Layers,
  ToggleLeft,
  SlidersHorizontal,
  Navigation,
  PanelLeft,
  Table2,
  FormInput,
  CalendarDays,
  Command,
  type LucideIcon,
  Orbit,
  Sparkles,
  Timer,
  MousePointerClick,
  GalleryHorizontalEnd,
  Activity,
  BarChart3,
  PieChart,
  TrendingUp,
  LineChart,
  Eye,
  Search,
  Fingerprint,
  ScanLine,
  BrainCircuit,
  Shield,
  Paintbrush,
  Palette,
  Component,
  Puzzle,
  Workflow,
  GitBranch,
  Route,
  FolderTree,
  Container,
} from 'lucide-react';

export type DnaStrand =
  | 'Reactive Pulse'
  | 'Atomic Bonding'
  | 'Cellular Composability'
  | 'The Catalyst';

export interface Material {
  id: string;
  code: string;
  name: string;
  category: string;
  packageName: string;
  description: string;
  purpose: string;
  icon: LucideIcon;
  dnaStrands: DnaStrand[];
  stability: number; // 0-100
  reactivity: 'Low' | 'Medium' | 'High' | 'Critical';
}

export interface Category {
  id: string;
  code: string;
  name: string;
  color: string;
  borderColor: string;
  bgColor: string;
  glowColor: string;
  description: string;
}

export const categories: Category[] = [
  {
    id: 'a-100',
    code: 'A-100',
    name: 'Structural',
    color: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
    bgColor: 'bg-cyan-500/10',
    glowColor: 'shadow-cyan-500/20',
    description: 'Foundation-level UI primitives. The bones of every interface.',
  },
  {
    id: 'b-200',
    code: 'B-200',
    name: 'Kinetic',
    color: 'text-fuchsia-400',
    borderColor: 'border-fuchsia-500/30',
    bgColor: 'bg-fuchsia-500/10',
    glowColor: 'shadow-fuchsia-500/20',
    description: 'Motion, animation, and temporal dynamics.',
  },
  {
    id: 'c-300',
    code: 'C-300',
    name: 'Analytical',
    color: 'text-emerald-400',
    borderColor: 'border-emerald-500/30',
    bgColor: 'bg-emerald-500/10',
    glowColor: 'shadow-emerald-500/20',
    description: 'Data visualization, charts, and logic rendering.',
  },
  {
    id: 'd-400',
    code: 'D-400',
    name: 'Sensory',
    color: 'text-amber-400',
    borderColor: 'border-amber-500/30',
    bgColor: 'bg-amber-500/10',
    glowColor: 'shadow-amber-500/20',
    description: 'Icons, imagery, feedback loops, and user perception.',
  },
  {
    id: 'e-500',
    code: 'E-500',
    name: 'Orchestral',
    color: 'text-rose-400',
    borderColor: 'border-rose-500/30',
    bgColor: 'bg-rose-500/10',
    glowColor: 'shadow-rose-500/20',
    description: 'Routing, state composition, and system-level coordination.',
  },
];

export const materials: Material[] = [
  // A-100 STRUCTURAL
  {
    id: 'a-101',
    code: 'A-101',
    name: 'Radix Dialog',
    category: 'a-100',
    packageName: '@radix-ui/react-dialog',
    description: 'Accessible modal overlay primitive with focus trapping.',
    purpose: 'Creates contained interaction spaces that demand user attention while preserving accessibility contracts.',
    icon: PanelLeft,
    dnaStrands: ['Atomic Bonding', 'Cellular Composability'],
    stability: 98,
    reactivity: 'Medium',
  },
  {
    id: 'a-102',
    code: 'A-102',
    name: 'Radix Tabs',
    category: 'a-100',
    packageName: '@radix-ui/react-tabs',
    description: 'Keyboard-navigable tabbed content panels.',
    purpose: 'Segments content into navigable planes without page transitions. Information architecture at the atomic level.',
    icon: Layers,
    dnaStrands: ['Atomic Bonding', 'Reactive Pulse'],
    stability: 97,
    reactivity: 'Low',
  },
  {
    id: 'a-103',
    code: 'A-103',
    name: 'Radix Select',
    category: 'a-100',
    packageName: '@radix-ui/react-select',
    description: 'Fully accessible dropdown selection primitive.',
    purpose: 'Collapses infinite choice into a single interaction point. The bridge between chaos and order.',
    icon: SlidersHorizontal,
    dnaStrands: ['Atomic Bonding', 'The Catalyst'],
    stability: 96,
    reactivity: 'Medium',
  },
  {
    id: 'a-104',
    code: 'A-104',
    name: 'Radix Accordion',
    category: 'a-100',
    packageName: '@radix-ui/react-accordion',
    description: 'Collapsible content sections with smooth transitions.',
    purpose: 'Progressive disclosure engine. Reveals complexity only when the Catalyst demands it.',
    icon: Boxes,
    dnaStrands: ['Cellular Composability', 'Reactive Pulse'],
    stability: 95,
    reactivity: 'Low',
  },
  {
    id: 'a-105',
    code: 'A-105',
    name: 'Radix Switch',
    category: 'a-100',
    packageName: '@radix-ui/react-switch',
    description: 'Binary toggle control with accessible labeling.',
    purpose: 'The simplest expression of user will: on or off, true or false. Pure Catalyst intent.',
    icon: ToggleLeft,
    dnaStrands: ['Atomic Bonding', 'The Catalyst'],
    stability: 99,
    reactivity: 'Low',
  },
  {
    id: 'a-106',
    code: 'A-106',
    name: 'Radix Navigation Menu',
    category: 'a-100',
    packageName: '@radix-ui/react-navigation-menu',
    description: 'Accessible site navigation with submenu support.',
    purpose: 'The wayfinding system. Maps the topology of the application so the Catalyst never gets lost.',
    icon: Navigation,
    dnaStrands: ['Cellular Composability', 'The Catalyst'],
    stability: 94,
    reactivity: 'Medium',
  },
  {
    id: 'a-107',
    code: 'A-107',
    name: 'Radix Scroll Area',
    category: 'a-100',
    packageName: '@radix-ui/react-scroll-area',
    description: 'Custom scrollable viewport with styled scrollbars.',
    purpose: 'Contains infinity within a viewport. Manages overflow so content breathes without breaking.',
    icon: Container,
    dnaStrands: ['Atomic Bonding'],
    stability: 93,
    reactivity: 'Low',
  },
  {
    id: 'a-108',
    code: 'A-108',
    name: 'CMDK',
    category: 'a-100',
    packageName: 'cmdk',
    description: 'Command palette interface for fast keyboard-driven navigation.',
    purpose: 'The speed layer. Bypasses visual hierarchy entirely — pure intent-to-action pipeline.',
    icon: Command,
    dnaStrands: ['Reactive Pulse', 'The Catalyst'],
    stability: 92,
    reactivity: 'Critical',
  },

  // B-200 KINETIC
  {
    id: 'b-201',
    code: 'B-201',
    name: 'Motion',
    category: 'b-200',
    packageName: 'motion',
    description: 'Production-grade animation library for React. Declarative springs, gestures, and layout animations.',
    purpose: 'The physics engine of the UI. Transforms static markup into living, breathing interfaces that respond to human touch.',
    icon: Orbit,
    dnaStrands: ['Reactive Pulse', 'The Catalyst', 'Cellular Composability'],
    stability: 97,
    reactivity: 'Critical',
  },
  {
    id: 'b-202',
    code: 'B-202',
    name: 'React DnD',
    category: 'b-200',
    packageName: 'react-dnd',
    description: 'Drag and drop primitives built on HTML5 drag events.',
    purpose: 'Grants the Catalyst spatial agency — the power to physically rearrange the digital world.',
    icon: MousePointerClick,
    dnaStrands: ['Reactive Pulse', 'The Catalyst'],
    stability: 90,
    reactivity: 'High',
  },
  {
    id: 'b-203',
    code: 'B-203',
    name: 'Embla Carousel',
    category: 'b-200',
    packageName: 'embla-carousel-react',
    description: 'Lightweight, extensible carousel engine with touch support.',
    purpose: 'Temporal navigation through content sequences. Time becomes a spatial axis the user traverses.',
    icon: GalleryHorizontalEnd,
    dnaStrands: ['Reactive Pulse', 'Cellular Composability'],
    stability: 93,
    reactivity: 'Medium',
  },
  {
    id: 'b-204',
    code: 'B-204',
    name: 'Vaul Drawer',
    category: 'b-200',
    packageName: 'vaul',
    description: 'Mobile-first drawer component with gesture-driven interaction.',
    purpose: 'Surfaces hidden dimensions with a pull gesture. The physical metaphor of revealing what lies beneath.',
    icon: PanelLeft,
    dnaStrands: ['Reactive Pulse', 'Atomic Bonding', 'The Catalyst'],
    stability: 91,
    reactivity: 'High',
  },
  {
    id: 'b-205',
    code: 'B-205',
    name: 'Sonner',
    category: 'b-200',
    packageName: 'sonner',
    description: 'Opinionated toast notification system with stacking and swipe-to-dismiss.',
    purpose: 'The system\'s voice. Temporal messages that appear, communicate, and gracefully exit the stage.',
    icon: Sparkles,
    dnaStrands: ['Reactive Pulse'],
    stability: 95,
    reactivity: 'Medium',
  },
  {
    id: 'b-206',
    code: 'B-206',
    name: 'React Day Picker',
    category: 'b-200',
    packageName: 'react-day-picker',
    description: 'Flexible date picker with range selection and localization.',
    purpose: 'Maps human time perception into selectable data. The bridge between the calendar and the database.',
    icon: CalendarDays,
    dnaStrands: ['Atomic Bonding', 'The Catalyst'],
    stability: 94,
    reactivity: 'Medium',
  },

  // C-300 ANALYTICAL
  {
    id: 'c-301',
    code: 'C-301',
    name: 'Recharts Line',
    category: 'c-300',
    packageName: 'recharts',
    description: 'Composable line chart built on D3 with responsive containers.',
    purpose: 'Renders temporal data as visual narrative. Each point is a moment; the line is the story.',
    icon: LineChart,
    dnaStrands: ['Cellular Composability', 'Reactive Pulse'],
    stability: 96,
    reactivity: 'Medium',
  },
  {
    id: 'c-302',
    code: 'C-302',
    name: 'Recharts Bar',
    category: 'c-300',
    packageName: 'recharts',
    description: 'Categorical comparison via proportional rectangular elements.',
    purpose: 'Makes magnitude tangible. The Catalyst can see relative truth at a glance.',
    icon: BarChart3,
    dnaStrands: ['Cellular Composability', 'Reactive Pulse'],
    stability: 96,
    reactivity: 'Medium',
  },
  {
    id: 'c-303',
    code: 'C-303',
    name: 'Recharts Pie',
    category: 'c-300',
    packageName: 'recharts',
    description: 'Radial composition charts showing part-to-whole relationships.',
    purpose: 'Reveals the hidden proportions within any whole. Turns raw numbers into spatial intuition.',
    icon: PieChart,
    dnaStrands: ['Cellular Composability'],
    stability: 94,
    reactivity: 'Low',
  },
  {
    id: 'c-304',
    code: 'C-304',
    name: 'Recharts Area',
    category: 'c-300',
    packageName: 'recharts',
    description: 'Filled line charts emphasizing volume and accumulation over time.',
    purpose: 'Visualizes weight and mass of data. The shaded region is potential energy made visible.',
    icon: TrendingUp,
    dnaStrands: ['Cellular Composability', 'Reactive Pulse'],
    stability: 95,
    reactivity: 'Medium',
  },
  {
    id: 'c-305',
    code: 'C-305',
    name: 'Date-fns',
    category: 'c-300',
    packageName: 'date-fns',
    description: 'Modular date utility library with tree-shakable functions.',
    purpose: 'The temporal algebra. Parses, formats, and computes across the fourth dimension so the Architect doesn\'t have to.',
    icon: Timer,
    dnaStrands: ['Atomic Bonding'],
    stability: 99,
    reactivity: 'Low',
  },

  // D-400 SENSORY
  {
    id: 'd-401',
    code: 'D-401',
    name: 'Lucide Icons',
    category: 'd-400',
    packageName: 'lucide-react',
    description: 'Comprehensive icon library with 1400+ consistent SVG icons.',
    purpose: 'The visual vocabulary. Every icon is a glyph that transcends language — universal human semiotics.',
    icon: Eye,
    dnaStrands: ['Atomic Bonding', 'Cellular Composability'],
    stability: 99,
    reactivity: 'Low',
  },
  {
    id: 'd-402',
    code: 'D-402',
    name: 'Radix Tooltip',
    category: 'd-400',
    packageName: '@radix-ui/react-tooltip',
    description: 'Accessible hover/focus tooltips with collision detection.',
    purpose: 'Contextual whispers. Information that appears only when curiosity demands it — respecting cognitive load.',
    icon: Search,
    dnaStrands: ['Atomic Bonding', 'The Catalyst'],
    stability: 97,
    reactivity: 'Low',
  },
  {
    id: 'd-403',
    code: 'D-403',
    name: 'Radix Avatar',
    category: 'd-400',
    packageName: '@radix-ui/react-avatar',
    description: 'Image avatar with fallback initials rendering.',
    purpose: 'The face of identity. Makes the digital feel human by anchoring data to a visual persona.',
    icon: Fingerprint,
    dnaStrands: ['Atomic Bonding'],
    stability: 98,
    reactivity: 'Low',
  },
  {
    id: 'd-404',
    code: 'D-404',
    name: 'Radix Progress',
    category: 'd-400',
    packageName: '@radix-ui/react-progress',
    description: 'Accessible progress bar with determinate/indeterminate states.',
    purpose: 'Maps completion into a spatial metaphor. The Catalyst sees exactly where they stand on any journey.',
    icon: Activity,
    dnaStrands: ['Reactive Pulse', 'The Catalyst'],
    stability: 96,
    reactivity: 'Medium',
  },
  {
    id: 'd-405',
    code: 'D-405',
    name: 'Radix Hover Card',
    category: 'd-400',
    packageName: '@radix-ui/react-hover-card',
    description: 'Rich content preview triggered by hover interaction.',
    purpose: 'Predictive information surfacing. Shows the Catalyst what lies behind a link before they commit to the click.',
    icon: ScanLine,
    dnaStrands: ['Atomic Bonding', 'The Catalyst'],
    stability: 93,
    reactivity: 'Medium',
  },

  // E-500 ORCHESTRAL
  {
    id: 'e-501',
    code: 'E-501',
    name: 'React Router',
    category: 'e-500',
    packageName: 'react-router',
    description: 'Declarative routing with nested layouts and data loading.',
    purpose: 'The nervous system. Routes are synapses connecting every region of the application into a coherent organism.',
    icon: Route,
    dnaStrands: ['Cellular Composability', 'Reactive Pulse', 'The Catalyst'],
    stability: 98,
    reactivity: 'Critical',
  },
  {
    id: 'e-502',
    code: 'E-502',
    name: 'React Hook Form',
    category: 'e-500',
    packageName: 'react-hook-form',
    description: 'Performant form state management with validation.',
    purpose: 'The Catalyst\'s voice captured in structured data. Transforms human intent into validated, typed payloads.',
    icon: FormInput,
    dnaStrands: ['Reactive Pulse', 'The Catalyst', 'Atomic Bonding'],
    stability: 97,
    reactivity: 'High',
  },
  {
    id: 'e-503',
    code: 'E-503',
    name: 'CVA',
    category: 'e-500',
    packageName: 'class-variance-authority',
    description: 'Type-safe class variant builder for component styling.',
    purpose: 'The DNA compiler for visual identity. Maps variant logic to deterministic style output — no ambiguity.',
    icon: Workflow,
    dnaStrands: ['Atomic Bonding', 'Cellular Composability'],
    stability: 96,
    reactivity: 'Low',
  },
  {
    id: 'e-504',
    code: 'E-504',
    name: 'Tailwind Merge',
    category: 'e-500',
    packageName: 'tailwind-merge',
    description: 'Intelligent Tailwind class conflict resolution.',
    purpose: 'The arbiter of style conflicts. When two classes fight for the same property, this decides the winner.',
    icon: GitBranch,
    dnaStrands: ['Atomic Bonding'],
    stability: 98,
    reactivity: 'Low',
  },
  {
    id: 'e-505',
    code: 'E-505',
    name: 'Resizable Panels',
    category: 'e-500',
    packageName: 'react-resizable-panels',
    description: 'Draggable panel layout system with persistence.',
    purpose: 'Hands spatial control to the Catalyst. The user sculpts their own workspace — architecture by intent.',
    icon: FolderTree,
    dnaStrands: ['Cellular Composability', 'The Catalyst'],
    stability: 92,
    reactivity: 'High',
  },
  {
    id: 'e-506',
    code: 'E-506',
    name: 'Radix Slot',
    category: 'e-500',
    packageName: '@radix-ui/react-slot',
    description: 'Polymorphic component composition via prop merging.',
    purpose: 'The shape-shifter. Allows any component to become any other — the ultimate expression of Cellular Composability.',
    icon: Puzzle,
    dnaStrands: ['Cellular Composability', 'Atomic Bonding'],
    stability: 99,
    reactivity: 'Low',
  },
];

export const dnaStrandInfo: Record<DnaStrand, { color: string; description: string }> = {
  'Reactive Pulse': {
    color: 'text-cyan-400',
    description: 'State-driven re-rendering. The heartbeat that keeps the UI alive and synchronized.',
  },
  'Atomic Bonding': {
    color: 'text-fuchsia-400',
    description: 'Prop contracts and type safety. The chemical bonds that hold components together.',
  },
  'Cellular Composability': {
    color: 'text-emerald-400',
    description: 'Nesting, slots, and compound patterns. Components that contain and extend other components.',
  },
  'The Catalyst': {
    color: 'text-amber-400',
    description: 'User intent and interaction. The human spark that activates every dormant possibility.',
  },
};
